version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "0"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ECR_SERVER=$(echo $ECR_REPOSITORY_URI | cut -d/ -f1)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_SERVER

      # commit id
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Commit hash is $COMMIT_HASH

      - IMAGE_TAG=$COMMIT_HASH
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image (Docker schema v2)...
      - docker build --platform linux/amd64 -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_URI:$IMAGE_TAG $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing images to ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:latest

      # - echo Updating Lambda function...

      # - aws lambda update-function-code \
      #   --function-name $LAMBDA_FUNCTION_NAME \
      #   --image-uri $ECR_REPOSITORY_URI:$IMAGE_TAG

      - echo Deployment completed
